spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:springcoredb

server:
  error:
    include-exception: false # Response에 Exception 표시 여부
    include-message: always # Response에 Exception Message 표시 여부
    include-stacktrace: on_param # Response에 Stack Trace 표시 여부