spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:springcoredb
    driver-class-name: org.h2.Driver
    username: sa
    password:

#spring:
#  datasource:
#    url: jdbc:mysql://ldudb.cs3wzmj0phr7.ap-northeast-2.rds.amazonaws.com:3306/postdb
#    username: admin
#    password: 12341234

  jpa:
    hibernate:
      format_sql: true
      show_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences:
#      ddl-auto: update


server:
  error:
    include-exception: false # Response에 Exception 표시 여부
    include-message: always # Response에 Exception Message 표시 여부
    include-stacktrace: on_param # Response에 Stack Trace 표시 여부
#  port: 9000

logging:
  level:
    me.ldu: DEBUG


jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400